### ISSUE TITLE
Request 2018 data

### ISSUE THREAD

**Issue by Allen616** [citizenlabsgr/openbudgetgr#5]

**Comment by Allen616** [comment]
Scott Buhrer is no longer the CFO for Grand Rapids, he retired 2 weeks ago. The new CFO is Jeff Dood. I have requested 2018 budget data from Jeff.

**Comment by jacebrowning** [comment]
Where are the raw 2016 and 2017 budgets hosted?

**Comment by Allen616** [comment]
The new CFO, Jeff Dood has said that his department may provide data in July. I uploaded the 2017 files on the [GR Open Data Portal](http://data.grcity.us/).  The files used for OpenBudgetGR are in my [Repo](https://github.com/Allen616/openbudgetgr/tree/master/_treemap).
